#!/bin/bash

ulimit -Sm $((1024 * 256))
ulimit -Sm $((1024 * 256))
ulimit -Sc unlimited

/opt/trac/venv/bin/twistd -n \
	--pidfile /opt/trac/run/twistd.pid \
	--logfile /opt/trac/log/twistd.log \
	--rundir /opt/trac/run \
	--python /opt/trac/server.tac
