version: '2'

services:
  names:
    image: names
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - external

  trac:
    image: trac
    depends_on:
      - postgres
    volumes:
      - ./tracconf:/srv/trac/trac-env/conf
      - ./tracfiles:/srv/trac/trac-env/files
    networks:
      - internal
      - external
    ports:
      - "9881:9881"

  amptrac:
    image: amptrac
    restart: always
    depends_on:
      - postgres
    networks:
      - internal
    ports:
      - "1352:1352"

  postgres:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5432:5432"


volumes:
  pgdata: {}
  tracconf: {}
  tracfiles: {}

networks:
  internal:
  external:
    driver: bridge
