version: '2'

services:
  trac:
    image: trac
    depends_on:
      - postgres
    volumes:
      - /Users/red/code/lookingglass/services/tracconf:/srv/trac/trac-env/conf
      - /Users/red/code/lookingglass/services/tracfiles:/srv/trac/trac-env/files
    networks:
      - internal
      - external
    ports:
      - "9881:9881"

  postgres:
    image: postgres:latest
    volumes:
      - /Users/red/code/lookingglass/services/pgdata:/var/lib/postgresql/data
    networks:
      - internal
volumes:
  pgdata: {}
  tracconf: {}
  tracfiles: {}

networks:
  internal:
  external:
    driver: bridge
